name = "signed-in-pit"
main = "src/index.js"
compatibility_date = "2026-08-31"

[durable_objects]
bindings = [{ name = "PIT", class_name = "PitRoom" }]

[[migrations]]
tag = "v1"
new_classes = ["PitRoom"]
